// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerateMaterialsPayload } from "./GenerateMaterialsPayload";
import type { SearchJobsPayload } from "./SearchJobsPayload";
import type { SubmitApplicationPayload } from "./SubmitApplicationPayload";

export type AircCommandPayload = { "kind": "search_jobs", "data": SearchJobsPayload } | { "kind": "generate_materials", "data": GenerateMaterialsPayload } | { "kind": "submit_application", "data": SubmitApplicationPayload };
