// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AircCommandPayload } from "./AircCommandPayload";
import type { CommandTransport } from "./CommandTransport";

export type AircCommand = { transport: CommandTransport, room: string, persona: string, command: string, payload: AircCommandPayload, capabilities: Array<string>, human_approval_required: boolean, };
