// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandTransport } from "./CommandTransport";
import type { ContinuumPhase } from "./ContinuumPhase";
import type { PhaseContext } from "./PhaseContext";

export type AircCommand = { transport: CommandTransport, room: string, persona: string, phase: ContinuumPhase, command: string, payload: PhaseContext, capabilities: Array<string>, human_approval_required: boolean, };
