// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsSummary = { variant_id: string, company: string, role_family: string, total: number, callbacks: number, interviews: number, rejections: number, callback_rate: number, interview_rate: number, };
