// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedAnswer } from "./GeneratedAnswer";
import type { TailoredCoverLetter } from "./TailoredCoverLetter";
import type { TailoredResume } from "./TailoredResume";

export type ApplicationPackage = { schema_version: string, variant_id: string, company: string, role_family: string, resume: TailoredResume, cover_letter: TailoredCoverLetter, generated_answers: Array<GeneratedAnswer>, };
