// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioArtifact } from "./PortfolioArtifact";
import type { Position } from "./Position";

export type ApplicationDraft = { variant: string, position: Position, selected_artifacts: Array<PortfolioArtifact>, resume_bullets: Array<string>, cover_letter: string, };
