// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalPolicy = { approvers: Array<string>, checkpoints: Array<string>, require_human_approval: boolean, };
