// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AircCommand } from "./AircCommand";
import type { ApplicationDraft } from "./ApplicationDraft";

export type ContinuumRecipe = { persona: string, room: string, variant: string, application: ApplicationDraft, commands: Array<AircCommand>, };
