// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuumResultStatus } from "./ContinuumResultStatus";

export type ContinuumResult = { status: ContinuumResultStatus, external_application_id: string | null, };
