// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContinuumCommand = "search-jobs" | "generate-materials" | "submit-application";
