// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AircCommand } from "./AircCommand";

export type ContinuumRecipe = { schema_version: string, variant_id: string, persona: string, room: string, commands: Array<AircCommand>, };
