// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContinuumPhase = "find_opportunities" | "enrich_opportunity" | "generate_materials" | "request_approval" | "submit" | "report_outcome" | "analyze_experiments";
