// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidencePack = { key: string, label: string, supporting_skills: Array<string>, supporting_domains: Array<string>, artifact_ids: Array<string>, };
