// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionBoundary = { schema_version: string, project_is_source_of_truth: boolean, continuum_recipe_required: boolean, notes: Array<string>, };
