// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeStatus } from "./OutcomeStatus";

export type ExperimentOutcome = { variant_id: string, company: string, role_family: string, outcome: OutcomeStatus, };
