// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoringWeights } from "./ScoringWeights";

export type ForkConfig = { schema_version: string, user_id: string, source_root: string, preferred_persona: string, preferred_room: string, scoring_weights: ScoringWeights, job_search_scope: Array<string>, voice_constraints: Array<string>, experimentation_rules: Array<string>, output_template: string, };
