// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GithubEvidence = { repository: string, title: string, summary: string, skills: Array<string>, domain_tags: Array<string>, url: string | null, };
