// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationDraft } from "./ApplicationDraft";
import type { ExperimentOutcome } from "./ExperimentOutcome";

export type InMemoryApplicationRepository = { applications: Array<ApplicationDraft>, experiments: Array<ExperimentOutcome>, };
