// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationPackage } from "./ApplicationPackage";
import type { ExperimentOutcome } from "./ExperimentOutcome";
import type { SubmissionRecord } from "./SubmissionRecord";

export type InMemoryApplicationRepository = { packages: Array<ApplicationPackage>, submissions: Array<SubmissionRecord>, experiments: Array<ExperimentOutcome>, };
