// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationQuestion } from "./ApplicationQuestion";

export type JobDossier = { schema_version: string, company: string, title: string, role_family: string, hiring_team: string | null, skills: Array<string>, domain_tags: Array<string>, responsibilities: Array<string>, application_questions: Array<ApplicationQuestion>, };
