// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalPolicy } from "./ApprovalPolicy";
import type { IdentityProfile } from "./IdentityProfile";
import type { PriorApplicationRecord } from "./PriorApplicationRecord";
import type { TargetPreferences } from "./TargetPreferences";
import type { VoiceProfile } from "./VoiceProfile";
import type { WorkPortfolio } from "./WorkPortfolio";

export type NormalizedPortfolio = { schema_version: string, user_id: string, profile: IdentityProfile, portfolio: WorkPortfolio, voice_profile: VoiceProfile, target_preferences: TargetPreferences, approval_policy: ApprovalPolicy, prior_applications: Array<PriorApplicationRecord>, };
