// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhaseContext = { variant_id: string, role_family: string, company: string, summary: string, approval_checkpoints: Array<string>, responsibilities: Array<string>, };
