// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationPackage } from "./ApplicationPackage";
import type { ContinuumRecipe } from "./ContinuumRecipe";
import type { ExecutionBoundary } from "./ExecutionBoundary";
import type { NormalizedPortfolio } from "./NormalizedPortfolio";
import type { PipelineStage } from "./PipelineStage";
import type { RankedEvidenceSet } from "./RankedEvidenceSet";
import type { SubmissionRecord } from "./SubmissionRecord";

export type PipelineOutputs = { schema_version: string, stages: Array<PipelineStage>, execution_boundary: ExecutionBoundary, normalized_portfolio: NormalizedPortfolio, ranked_evidence: RankedEvidenceSet, application_package: ApplicationPackage, continuum_recipe: ContinuumRecipe, submission_record: SubmissionRecord, };
