// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PipelineStageKind = "source_ingestion" | "evidence_shaping" | "application_generation" | "outcome_capture";
