// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineStageKind } from "./PipelineStageKind";

export type PipelineStage = { stage: PipelineStageKind, description: string, };
