// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSource } from "./ArtifactSource";

export type PortfolioArtifact = { id: string, source: ArtifactSource, title: string, organization: string | null, summary: string, skills: Array<string>, evidence: string | null, };
