// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Position = { title: string, company: string, hiring_team: string | null, skills: Array<string>, };
