// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeStatus } from "./OutcomeStatus";

export type PriorApplicationRecord = { company: string, role: string, role_family: string, variant_id: string, status: OutcomeStatus, notes: string | null, rejection_reason: string | null, };
