// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSource = { title: string, summary: string, repository: string | null, skills: Array<string>, domain_tags: Array<string>, };
