// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioArtifact } from "./PortfolioArtifact";

export type RankedArtifact = { artifact: PortfolioArtifact, score: number, matched_skills: Array<string>, matched_domains: Array<string>, };
