// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidencePack } from "./EvidencePack";
import type { RankedArtifact } from "./RankedArtifact";

export type RankedEvidenceSet = { schema_version: string, variant_id: string, company: string, role_family: string, ranked_artifacts: Array<RankedArtifact>, evidence_packs: Array<EvidencePack>, };
