// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScoringWeights = { skill_match_weight: number, domain_match_weight: number, evidence_bonus_weight: number, };
