// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchJobsPayload = { title: string, company: string, skills: Array<string>, };
