// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSource } from "./ArtifactSource";

export type SkillStrength = { skill: string, count: number, sources: Array<ArtifactSource>, };
