// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationDelegation } from "./AutomationDelegation";
import type { PortfolioArtifact } from "./PortfolioArtifact";
import type { Position } from "./Position";
import type { VoiceProfile } from "./VoiceProfile";

export type SubmitApplicationPayload = { variant: string, position: Position, voice_profile: VoiceProfile, selected_artifacts: Array<PortfolioArtifact>, resume_bullets: Array<string>, cover_letter: string, automation: AutomationDelegation, };
