// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionWorkflowStatus = "awaiting_human_approval" | "ready_to_dispatch" | "awaiting_continuum_result" | "submitted";
