// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuumResult } from "./ContinuumResult";

export type SubmissionEvent = { "type": "approve", actor: string, } | { "type": "dispatch", dispatch_id: string, persona: string | null, room: string | null, } | { "type": "continuum_result", result: ContinuumResult, };
