// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision";
import type { SubmissionStatus } from "./SubmissionStatus";

export type SubmissionRecord = { schema_version: string, variant_id: string, company: string, role_family: string, status: SubmissionStatus, approvals: Array<ApprovalDecision>, feedback: string | null, rejection_reason: string | null, };
