// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuumRecipe } from "./ContinuumRecipe";
import type { ContinuumResult } from "./ContinuumResult";
import type { SubmissionDispatch } from "./SubmissionDispatch";
import type { SubmissionWorkflowStatus } from "./SubmissionWorkflowStatus";

export type SubmissionWorkflow = { recipe: ContinuumRecipe, approval_assignee: string, status: SubmissionWorkflowStatus, history: Array<string>, dispatch: SubmissionDispatch | null, result: ContinuumResult | null, };
