// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetPreferences = { preferred_roles: Array<string>, preferred_companies: Array<string>, preferred_locations: Array<string>, keywords: Array<string>, };
