// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalPolicy } from "./ApprovalPolicy";
import type { GithubEvidence } from "./GithubEvidence";
import type { IdentityProfile } from "./IdentityProfile";
import type { PriorApplicationRecord } from "./PriorApplicationRecord";
import type { ProjectSource } from "./ProjectSource";
import type { SkillTag } from "./SkillTag";
import type { TargetPreferences } from "./TargetPreferences";
import type { VoiceExample } from "./VoiceExample";
import type { WorkHistoryItem } from "./WorkHistoryItem";

export type UserSourceBundle = { schema_version: string, identity_profile: IdentityProfile, work_history: Array<WorkHistoryItem>, projects: Array<ProjectSource>, github_evidence: Array<GithubEvidence>, skill_tags: Array<SkillTag>, voice_examples: Array<VoiceExample>, target_preferences: TargetPreferences, prior_applications: Array<PriorApplicationRecord>, approval_policy: ApprovalPolicy, };
