// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkHistoryItem = { company: string, role: string, summary: string, skills: Array<string>, domain_tags: Array<string>, };
