// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioArtifact } from "./PortfolioArtifact";
import type { SkillStrength } from "./SkillStrength";

export type WorkPortfolio = { artifacts: Array<PortfolioArtifact>, strengths: Array<SkillStrength>, };
